### ISSUE TITLE
ovirt-img: Machine readable progress

### ISSUE THREAD

**Issue by aesteve-rh** [oVirt/ovirt-imageio#154]
Support machine readable progress, usable by program running ovirt-img.

When running ovirt-img with a command line option, it will output progress info to stdout
in [jsonlines](https://jsonlines.org/) format:

```
{"transferred": 249561088, "size": 261095424, elapsed: 1.234567, "description": "Copying disk"}
{"transferred": 256901120, "size": 261095424, elapsed: 1.345678, "description": "Copying disk"}
{"transferred": 261095424, "size": 261095424, elapsed: 1.456789, "description": "Finalizing transfer"}
```

Program using ovirt-img will read stdout line by line, parsing the json message from each line.

Fields:
- `size`: int64, optional. Imageio know the size only after connecting to imageio server. During the first few seconds when the size is unknown, the system cannot report any progress value.
- `transferred`: int64, required
- `elapsed`: float, required
- `description`: string, required

## MTV use case

It can work like this:

- Add progress info to the CRD related to the import job

  Example yaml fragment:
  ```
  status:
    progress:
        transferred: 249561088
        size: 261095424
        elapsed: 1.234567
        description: "Copying disk"
  ```
- The UI watches the CR during the transfer
- The program running ovirt-img read progress line and update the import CR status
- The UI update progress bar based on CR change events
